version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: koi#1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: koi
      MYSQL_PASSWORD: koi#1

  wordpress:
    links:
      - db
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./:/var/www/html/wp-content
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: koi
      WORDPRESS_DB_PASSWORD: koi#1
volumes:
  db_data: